# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-24 13:53
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_create_admin', 'Can create admin'), ('can_create_co_admin', 'Can create co-admin'), ('can_create_volunteer', 'Can create volunteer'), ('can_create_participant', 'Can create participant'), ('can_edit_admin', 'Can edit admin'), ('can_edit_co_admin', 'Can edit co-admin'), ('can_edit_volunteer', 'Can edit volunteer'), ('can_edit_participant', 'Can edit participant'), ('can_delete_admin', 'Can delete admin'), ('can_delete_co_admin', 'Can delete co-admin'), ('can_delete_volunteer', 'Can delete volunteer'), ('can_delete_participant', 'Can delete participant')),
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
