# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-24 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(choices=[(1, 'Admin'), (2, 'Co-admin'), (3, 'Volunteer'), (4, 'Participant')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together=set([('user', 'profile')]),
        ),
    ]
